### ISSUE TITLE
Modal/Popup/Helpbox warning about expungement price

### ISSUE THREAD

**Issue by ejmg** [codeforkansascity/expungement#21]
As discussed 11.03.19 with UX, the financial cost of expungement is a high priority for end users. It would be best to put a warning up front about this cost for now, so long as CMR doesn't provide a means directly to alleviate or cover this cost (by or after the clinic MVP)

**Comment by zmon** [comment]
Closing this since qualifying questions were not used, and we are not sure if they will be used.
