### ISSUE TITLE
Move qualifying answers from disqualifying-question.vue component into section-do-you-qualify.vue

### ISSUE THREAD

**Issue by ejmg** [codeforkansascity/expungement#24]
In the ideal future where we feed in text from our API for qualifying questions and qualifying answers, this will be less of an issue. For now, however, we should refactor our code from having the qualifying answers in `disqualifying-question.vue` and move it into the `section-do-you-qualify.vue` component

**Comment by ejmg** [comment]
@nucle0tides may be able to phrase this better than me

**Comment by zmon** [comment]
Changed from section-do-you-qualify.vue to qualifying-question.vue since it is a question and not a section containing questions.
